name: Build apk
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      # workaround for "build-tool 31.0.0 is missing DX at /usr/local/lib/android/sdk/build-tools/31.0.0/dx"
      # see: https://github.com/actions/virtual-environments/issues/3757#issuecomment-883646793
      - run: |
          SDKMANAGER=$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager
          echo y | $SDKMANAGER --uninstall "build-tools;31.0.0"
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: build the apk
        run: |
          npm install --frozen-lockfile
          npm run build:android
          npm run build:android-debug
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - uses: actions/upload-artifact@v2
        with:
          path: |
            platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
            platforms/android/app/build/outputs/apk/debug/app-debug.apk
